[package]
name = "unirennes-manuscript"
version = "0.3.1"
entrypoint = "src/lib.typ"
authors = [
  "Timothé Albouy",
  "Augustin Godinot <augustin.godinot@inria.fr>"
]
license = "Unlicense"
description = "Unofficial Typst template to create a thesis manuscript using Université de Rennes and Collège Doctoral de Bretagne charter"
repository = "https://github.com/grodino/unirennes-manuscript-typst"
keywords = [ ]
categories = [ "thesis" ]
disciplines = [ ]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile"
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = ""
